/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.applet.AudioClip;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac Bustamante
 */
public class preguntas extends javax.swing.JFrame {

    /**
     * Creates new form preguntas
     */    
    static Random aleatorio = new Random();
    public static int opcion;
    static String respuestas[] = {"thor","estrella","infinito","natasha","millones","no","reactor arc","mioldir","loki","tiempo"};
    static AudioClip bonus1;
    public static inicio i = new inicio();
    public preguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
        opcion = aleatorio.nextInt(10);   
        txtAreaPreguntas.setEnabled(false);
        
        switch(opcion){
            case 0:
                txtAreaPreguntas.setText("¿Cual es el personaje que porta el martillo del dios del trueno?");
                break;
            case 1:
                txtAreaPreguntas.setText("¿Cual es la figura del escudo del capitan america?");
                break;
            case 2:
                txtAreaPreguntas.setText("¿Que gemas buscaba thanos?");
                break;
            case 3:
                txtAreaPreguntas.setText("¿Quien muere por la gema de la mente?");
                break;
            case 4:
                txtAreaPreguntas.setText("Completa la oracion -> Te amo 3...");
                break;
            case 5:
                txtAreaPreguntas.setText("Hulk le gana a thanos ¿Si o no?");
                break;
            case 6:
                txtAreaPreguntas.setText("¿Que tiene IRON MAN en el pecho?");
                break;
            case 7:
                txtAreaPreguntas.setText("Como se llama el martillo de Thor");
                break;
            case 8:
                txtAreaPreguntas.setText("El dios del engaño es:");
                break;
            case 9:
                txtAreaPreguntas.setText("El Dr. Strange tiene la gema del...");
                break;
            default:
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAreaPreguntas = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        txtRes = new javax.swing.JTextField();
        btnRespuesta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaPreguntas.setFont(new java.awt.Font("Blackadder ITC", 1, 14)); // NOI18N
        txtAreaPreguntas.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(txtAreaPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 460, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Respuesta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, 40));

        txtRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResActionPerformed(evt);
            }
        });
        getContentPane().add(txtRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, 40));

        btnRespuesta.setBackground(new java.awt.Color(102, 0, 102));
        btnRespuesta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        btnRespuesta.setText("Responder");
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResActionPerformed

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        //System.out.println(opcion);
        String res = txtRes.getText();
        System.out.println(opcion);
        for (int i = 0; i < respuestas.length; i++) {
            if (opcion == i) {
                System.out.println(i);
                System.out.println(respuestas[i]);
                System.out.println(res);
                if (res != respuestas[i]) {
                    bonus1 = java.applet.Applet.newAudioClip(getClass().getResource("/musica/ringtones-the-avengers.wav"));
                    bonus1.play();       
                    JOptionPane.showMessageDialog(null,"Felicidades haz pasado el nivel");
                    System.exit(0);
                    //inicio.setVisible(true);
                }
            }
        }

    }//GEN-LAST:event_btnRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        //Preguntas(opcion);
//        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new preguntas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextArea txtAreaPreguntas;
    private javax.swing.JTextField txtRes;
    // End of variables declaration//GEN-END:variables
}
